### ISSUE TITLE
[Bug] Changes made in settings do not survive app restart

### ISSUE THREAD

**Issue by tuplasuhveli** [sailfishos-applications/flowplayer#99] opened 2024-06-08 13:43 UTC
**SailfishOS VERSION** 4.5.0.25 
<br />**HARDWARE** Sony Xperia 10 III
<br />**FlowPlayer VERSION** 0.3.5
<br />

#### BUG DESCRIPTION

Any changes made in the Settings page are switched back to default after restarting the app. This is problematic especially when changing the language, since applying a new language requires a restart, but the change in the settings is reverted at restart.

#### STEPS TO REPRODUCE

1. Open the top pulley menu to go into Settings.
2. Change any setting you desire.
3. Restart the app.
4. Notice the change being reverted back to default.

#### ADDITIONAL INFORMATION

When using "Manage folders", the changes are not reverted, even though no folders are shown in the list after a restart.

**Comment by Olf0** [comment] 2024-06-16 00:48
@tuplasuhveli, thank you for your concise bug report.

On a pre-SailJail installation of SailfishOS (3.2.1) this issue is not reproducible with FlowPlayer 0.3.5: Changes in FlowPlayer's settings survived closing and then starting FlowPlayer again.

As sandboxing was introduced by v0.3.5 (see PR #77) you can check with FlowPlayer 0.3.4 that this bug is related to it.  I assume so, but better be sure.

Spontaneously I can think of two reasons:
1. (Some or all) saved settings are in a location outside a SailJail permitted path.
   This should not be the case AFAIR, but has to be checked.
   Jolla provides some guidance for debugging apps trying to violate SailJail permissions: [sailfishos/sailjail/APPDEBUG.md](https://github.com/sailfishos/sailjail/blob/master/APPDEBUG.md#debugging-sailjail-application-sandboxing)  Maybe you have time and motivation to go through this guidance.
2. A permission is wrongly used or missing, see [sailfishos/sailjail-permissions/README.md](https://github.com/sailfishos/sailjail-permissions#readme) for details.
   This README contains a list of accesses an app is allowed to do: AFAICS FlowPlayer's settings are within that, but this needs to be checked thoroughly.
   The SailJail permissions FlowPlayer currently acquires [can be seen here](https://github.com/sailfishos-applications/flowplayer/blob/devel/flowplayer.desktop#L13).

Maybe @dcaliste (co-author of PR #77) or @poetaster (original author of PR #77) has an idea what goes wrong here.

P.S.: @tuplasuhveli, I wonder a bit why nobody else complained since the release of FlowPlayer 0.3.5: This should affect almost all users (i.e. all users of FlowPlayer 0.3.5 on SailfishOS ≥ 4.3.0).

P.P.S.: Note that I am neither using FlowPlayer or writing code for it; I merely coordinate its maintenance and take care about release management, translations infrastructure and automatisation, CI workflows, GH repo config, RPM packaging, keeping READMEs up-to-date, etc.

**Comment by tuplasuhveli** [comment] 2024-06-27 11:41
Hey @Olf0, I'm so sorry I had completely missed your reply. 

Apparently the issue seems to be fixed now, but since I broke my only phone capable of running SFOS, I'm not able to test the fix. Thank you both, especially @dcaliste for doing the hard work!

**Closed** 2024-07-04 19:50 UTC
Labels: bug

**Comment by Olf0** [comment] 2024-11-27 22:23
@RTheren, thank you for reporting that this appears to be an issue (either "still" or "again").

Unfortunately I have no idea, because I do not know much about SailJail / Firejail and I do not use FlowPlayer (I just barely manage its maintenance, releases, infrastructure etc.).

Maybe @dcaliste has an idea how address this.

**Comment by RTheren** [comment] 2024-11-28 07:55
Thank you Olf. Once it's out, I will retest it and post here if it happens again :)

**Comment by Olf0** [comment] 2024-11-29 00:57
> Once it's out, I will retest it and post here if it happens again :)

Can you please manually install the RPM file for `aarch64` from the ZIP-archive for SailfishOS 4.3.0.12+ of [FlowPlayer 0.3.6 on GitHub's releases page](https://github.com/sailfishos-applications/flowplayer/releases/tag/release4%2F0.3.6).
*Edit:* Or more conveniently from SailfishOS:Chum:**Testing**, which e.g. can be selected in the settings of the SailfishOS:Chum GUI app.

As you offered to test it, I gladly use your offer to avoid releasing an untested version at OpenRepos and SailfishOS:Chum.

Thank you very much!

**Comment by RTheren** [comment] 2024-11-29 12:30
I've downloaded the RPM from Release page and installed it. Can confirm the settings are indeed preserved after restarting.

**Comment by Olf0** [comment] 2024-12-02 01:00
Thanks for testing: FlowPlayer 0.3.6 is available at OpenRepos and SailfishOS:Chum now.
